Group:
  type: entity
  table: groups
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: varchar
      length: 32
    description:
      type: text